class User {
  final String uid;
  final int? userId; // Assuming this will be auto-generated by the database
  final String userName;
  final DateTime? lastLogin;
  final DateTime dateCreated;
  final String userStatus;

  User(
    this.uid,
    this.userId,
    this.userName,
    this.lastLogin,
    this.dateCreated,
    this.userStatus,
  );

  User.fromMap(Map<String, dynamic> map)
      : uid = map['uid'],
        userId = map['userId'],
        userName = map['userName'],
        lastLogin = map['lastLogin'],
        dateCreated = map['dateCreated'],
        userStatus = map['userStatus'];

  Map<String, dynamic> toMap() {
    return {
      'uid': uid,
      'userId': userId,
      'userName': userName,
      'lastLogin': lastLogin,
      'dateCreated': dateCreated,
      'userStatus': userStatus,
    };
  }

  @override
  String toString() {
    return 'User{uid: $uid, userId: $userId, userName: $userName, lastLogin: $lastLogin, dateCreated: $dateCreated, userStatus: $userStatus}';
  }
}
