// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqNDtcw4PgNP_j1zpOw_1J410onKzNQZM',
    appId: '1:1040409079041:android:c32c9ea4197ccdc59f3f00',
    messagingSenderId: '1040409079041',
    projectId: 'swapit-app-942b1',
    storageBucket: 'swapit-app-942b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnzpKmhzo3FJbu6J7dH1XvAcheqxsik2g',
    appId: '1:1040409079041:ios:0599efdeabafaf299f3f00',
    messagingSenderId: '1040409079041',
    projectId: 'swapit-app-942b1',
    storageBucket: 'swapit-app-942b1.appspot.com',
    androidClientId: '1040409079041-j34dgi8rjai50cc9vbf32s3bdsiccl6r.apps.googleusercontent.com',
    iosClientId: '1040409079041-3189siu30d6blha1huejfrqdo8774vrj.apps.googleusercontent.com',
    iosBundleId: 'com.example.swapitApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQV2S2XlFlBvK7tODQRYhKc0AwHn6OZBg',
    appId: '1:1040409079041:web:1c4109cfb3a6071a9f3f00',
    messagingSenderId: '1040409079041',
    projectId: 'swapit-app-942b1',
    authDomain: 'swapit-app-942b1.firebaseapp.com',
    storageBucket: 'swapit-app-942b1.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnzpKmhzo3FJbu6J7dH1XvAcheqxsik2g',
    appId: '1:1040409079041:ios:0599efdeabafaf299f3f00',
    messagingSenderId: '1040409079041',
    projectId: 'swapit-app-942b1',
    storageBucket: 'swapit-app-942b1.appspot.com',
    androidClientId: '1040409079041-j34dgi8rjai50cc9vbf32s3bdsiccl6r.apps.googleusercontent.com',
    iosClientId: '1040409079041-3189siu30d6blha1huejfrqdo8774vrj.apps.googleusercontent.com',
    iosBundleId: 'com.example.swapitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQV2S2XlFlBvK7tODQRYhKc0AwHn6OZBg',
    appId: '1:1040409079041:web:6abaec7bcc14c8ea9f3f00',
    messagingSenderId: '1040409079041',
    projectId: 'swapit-app-942b1',
    authDomain: 'swapit-app-942b1.firebaseapp.com',
    storageBucket: 'swapit-app-942b1.appspot.com',
  );

}